# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

pool:
  vmImage: 'macOS-10.15'
steps:
  - task: GoTool@0
    inputs:
      version: '1.16.3'
  - task: NodeTool@0
    inputs:
      versionSpec: '15.x'
  - script: |
      npm install
      make all -j $(nproc --all 2>/dev/null || sysctl -n hw.ncpu)
      ELECTRON=1 FRONTEND_APP=mmseqs node ./electron/build.js
  - task: DownloadSecureFile@1
    name: certificate
    inputs:
      secureFile: certificate.p12
  - task: CmdLine@2
    inputs:
      script: ./node_modules/.bin/electron-builder -mwl
    env:
      CSC_LINK: $(certificate.secureFilePath)
      CSC_KEY_PASSWORD: $(CSC_KEY_PASSWORD)
      GH_TOKEN: $(GH_TOKEN)
