version: '2'

services:
  mmseqs-web-redis:
    image: redis:alpine
    volumes:
      - redis-volume:/var/lib/redis

  mmseqs-web-api:
    image: "soedinglab/mmseqs2-app-backend:${TAG}"
    command: -server -config /etc/mmseqs-web/config.json
    depends_on:
      - mmseqs-web-redis
    expose:
      - "3000"
    volumes:
      - ./config.json:/etc/mmseqs-web/config.json:ro
      - ./databases:/opt/mmseqs-web/databases
      - ./jobs:/opt/mmseqs-web/jobs

  mmseqs-web-worker:
    image: "soedinglab/mmseqs2-app-backend:${TAG}"
    command: -worker -config /etc/mmseqs-web/config.json
    depends_on:
      - mmseqs-web-api
      - mmseqs-web-redis
    volumes:
      - ./config.json:/etc/mmseqs-web/config.json:ro
      - ./databases:/opt/mmseqs-web/databases
      - ./jobs:/opt/mmseqs-web/jobs
    tmpfs:
      - /tmp:exec

  mmseqs-web-webserver:
    image: "soedinglab/mmseqs2-app-frontend:${TAG}"
    depends_on:
      - mmseqs-web-api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${PORT}:80"

volumes:
  redis-volume:

